### ISSUE TITLE
Some qustions about the setup

### ISSUE THREAD

**Issue by VolcanoWCAN** [juaiglesias/ehrecords-hyperledger-blockchain#2]
Hi, author: 
I find that your project excellent and I want to learn from your source code.
But now I have a question.
I want to know where should I run the command "GET /admin/" ?
The instruction says "Run GET /admin/ in the backend to enroll admin"
But I don't understand what it means.
Could you please explain the details?

Thank you very much!

**Comment by VolcanoWCAN** [comment]
test

**Comment by VolcanoWCAN** [comment]
I  had installed the mangodb.

       When I run "cnpm run dev", the error happens:

> backend@1.0.0 dev /home/ehrecords-hyperledger-blockchain/web-app/backend
> nodemon server.js

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
**Error connecting to the database: MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.**
Server is running on port 5000**

When I visit the web http://localhost:5000/，the web shows that:
**Cannot GET /**

Should I modify the configuration of the database? And how can I solve this problem?

**Comment by VolcanoWCAN** [comment]
I run npm run dev

The log outputs：


[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
Server is running on port 5000
Error connecting to the database: MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.

**Comment by VolcanoWCAN** [comment]
Hi author：
I had sent an email to you about my quetions. I talked about my puzzles detailly in this email.
I am looking forward to hearing from you soon.
And thank you very much!

**Comment by juaiglesias** [comment]
The doubts were resolved by email. I will pay attention to issues next time, sorry!
I added more documentation in order to make this clear for other people.
